### ISSUE TITLE
New version JSON lint search not working

### ISSUE THREAD

**Issue by ojoven** [circlecell/jsonlint.com#103]
Hey, the change looks nice, thanks for adding dark mode!
I'm afraid, though, that the search functionality is not working anymore and it's a pity because it's a function that I assume it's widely used.

Thanks in any case for all your work on this!

**Comment by toddynho** [comment]
Sorry about that! Added back search, and also added a copy to clipboard button while in there.

We also released a chrome formatting plugin in case that is of any interest: https://chrome.google.com/webstore/detail/json-formatter/ondecobpcidaehknoegeapmclapnkgcl?hl=en&authuser=1

If there are any other improvements you'd like to see just met me know!
