### ISSUE TITLE
Characters being escaped when they shouldn't

### ISSUE THREAD

**Issue by lucas2595** [circlecell/jsonlint.com#106]
When I input:
```
{
    "quotationmark": "\"",
    "solidus": "\\",
    "reversesolidus": "\/",
    "backspace": "\b",
    "formfeed": "\f",
    "newline": "\n",
    "carriagereturn": "\r",
    "horizontaltab": "\t",
    "unicode": "\u00e7"
}
```
According to https://www.json.org/json-en.html, I expect it to be kept as is.
![image](https://github.com/circlecell/jsonlint.com/assets/24466413/3d0a7df9-0641-4573-a54b-023fee1ab2de)

But the reverse solidus and the unicode sequence get broken when I validate:
```
{
    "quotationmark": "\"",
    "solidus": "\\",
    "reversesolidus": "\\/",
    "backspace": "\b",
    "formfeed": "\f",
    "newline": "\n",
    "carriagereturn": "\r",
    "horizontaltab": "\t",
    "unicode": "\\u00e7"
}
```

**Comment by henninghh990** [comment]
Hope this will be fixed soon. Can't use jsonlint when editing JSON-objects where there are text in norwegian or swedish, since double backslashes are added to every "foreign" letter such as \u00f8 and \u00e5.

**Comment by toddynho** [comment]
This should be fixed now.
