### ISSUE TITLE
Excessive escaping of html entities on jsonlint.com

### ISSUE THREAD

**Issue by kajman-cz** [circlecell/jsonlint.com#107]
In the Common Errors section on [jsonlint.com](https://jsonlint.com/) are escaped & to &amp;amp; in html entities &amp;lbrace; and &amp;rbrace; and examples show this entities instead of { and }.

![screenshot](https://github.com/circlecell/jsonlint.com/assets/45236547/fd00a798-d6bc-4b29-874c-d3c3f23c4d1a)

**Comment by toddynho** [comment]
thank you, fixed this over here on the new repo: https://github.com/circlecell/jsonlint/commit/08e0621ec1919a963b530d8a57b5813bf72004ca
