### ISSUE TITLE
Search via cmd+f on mac's chrome does not find all occurrences

### ISSUE THREAD

**Issue by emanuelthedude** [circlecell/jsonlint.com#62]
First of all thanks. This is an awesome jsonlinter. I'm using it a lot and love it!!

I can not search with the normal browser search (cmd+f ) in the pasted json. It seems that it is only searching in the user visible area but not in the whole json.

Im using a MacBook Pro (Retina, 13-inch, Early 2015) with macOS Sierra 10.12.4 (16E195) and Chrome Version 58.0.3029.110 (64-bit)

Steps to reproduce:
1. paste a json with more than 60 lines to jsonlint.com
2. search for a string with cmd+f that is not in the visible area of jsonlint's input field

**Comment by finom** [comment]
Done for https://jsonlint.com and https://jsoncompare.com
