### ISSUE TITLE
what happened to `pro.jsonlint.com` ?

### ISSUE THREAD

**Issue by tswaters** [circlecell/jsonlint.com#63]
It used to be this would be a full-screen page with a single textbox and a lint button - now it is redirecting to `https://jsoncompare.com/#!/simple/` which has more bells/whistles.

Could it at least redirect to `https://jsoncompare.com/#!/simple/fullscreen/` ?

**Comment by finom** [comment]
@tswaters you should press the button, it's quite easy

**Comment by tswaters** [comment]
The full screen mode is no an extra click of a button to get there.  

It would be great if `pro.jsonlint` redirected to the full screen mode.

**Comment by tswaters** [comment]
Also, the default operation before was to beautify the JSON after pressing `lint` - now this is an extra click away under the "Keep JSON as" dropdown.

All in all, I'm not liking this new version...  before it was a single button click and was, as you say, quite easy.... now there are more things that need to be pressed to get the same behavior.

I may need to create my own page that has the full screen textbox and a single button.
