### ISSUE TITLE
Please reintroduce the ability to have multiple linters open in one page

### ISSUE THREAD

**Issue by RyanMitchellWilson** [circlecell/jsonlint.com#64]
The old pro.jsonlint.com used to be able to have multiple linters open at once on one page. Now I have to have a tab for every chunk of JSON that I want to look at, which makes it hard to remember which tab is the correct one for what I'm looking for. Reintroducing this functionality would be awesome!

Also on a side note, I really liked the fact that the old site was full screen and beautified your tabs by default, but it is not the biggest deal having to choose those options.

**Comment by finom** [comment]
@RyanMitchellWilson why not to use "batch" tab? It plays the same role as "pro" did.

**Comment by RyanMitchellWilson** [comment]
Ok cool thanks for the response, is it possible to get those linters in the batch tab to be side by side instead of on top of one another?

**Comment by finom** [comment]
@RyanMitchellWilson use diff mode :)
https://jsoncompare.com/#!/diff/

**Comment by RyanMitchellWilson** [comment]
This diff mode is pretty handy, I really like it for trying to see differences, but is there a way to have two different linters open that are not trying to compare? While checking the diffs is really helpful for the most part, there are occasions I just want to have two different json chunks open without directly comparing the two.
