### ISSUE TITLE
Please bring back pro.jsonlint.com

### ISSUE THREAD

**Issue by jamesaspence** [circlecell/jsonlint.com#65]
The original pro.jsonlint.com was radically better than the newly-redirected jsoncompare.com. Can we get the original source code (or the original site) back up? If you guys aren't interested in continuing to maintain it, I'd be happy to take a stab at it, just to keep that original site up.

**Comment by jamesaspence** [comment]
Just for clarification, I am referring to this version of the site: http://web.archive.org/web/20160201194007/http://pro.jsonlint.com:80/

**Comment by speckyboy** [comment]
Thanks James!

We've put a ton of work into JSONCompare.com and felt that we had made a better tool. Could you tell us what exactly it is you don't like about it?

**Comment by jamesaspence** [comment]
Absolutely. The thing I mainly like about the old version is the simplicity - just paste in your JSON and have it formatted to four spaces. No extra clicks or additional button presses required. I appreciate the fact that the new version has extra features (ability to set linting options, batch), but those all take away from the main experience for me, which was spacing out my JSON and being able to view it in a minimalist, non-intrusive window.

That's my main issue with the new version - to get the same results as the original, I have to:
- go to the site
- click fullscreen editor
- Set my beautify settings (by default it appears to set to tabs, so this might have been changed in my favor recently).

So I think I misspoke when I said, _radically better_. What I meant to say was, more _minimalist_ and _well-suited_ for my flow specifically. However, I'm sure I'm not the only one!

PS: Sorry for the long response time. Your reply kinda got lost in the noise.

**Comment by finom** [comment]
@jamesaspence 
- The original pro.jsonlint had lots of issues which were fixed at JSONCompare (line mismatch when long json objects are used, no syntax highlighting, etc.).
- You don't have to click at Fullscreen button every time if you open JSONCompare from your Bookmarks. All your preferences are stored at URL.
- Per your (and other) request beautifying by tab is now set by default.
