### ISSUE TITLE
The clear button also clears "Results"

### ISSUE THREAD

**Issue by nelsonmarcos** [circlecell/jsonlint.com#68]
I think it would be nice if the clear button clears the "Results" message so the user can be sure that he/she is not seeing a cached result after a new validation.

**Comment by speckyboy** [comment]
Thanks @nelsonmarcos, that makes sense. I've added it to our 'to-review' list and we'll discuss a solution.

**Comment by Luuk34** [comment]
This discuss takes loooong….. 😒
