### ISSUE TITLE
Add option to view old design

### ISSUE THREAD

**Issue by Supertecnoboff** [circlecell/jsonlint.com#70]
JSONLint is a fantastic website, but please can you add an option to use the old design? I don't like the new design because:

1) It is full of adverts.
2) The JSON editor is tiny. The old design used the entire screen which made for a much cleaner experience. I also liked the colour scheme of the old design, it was easy on the eyes.

Please please bring back the old design or add an option for it.

**Comment by willtrking** [comment]
Addition to that, the old linter would "beautify" json-like structures (such as python dict dumps) into a more readable format, which is super handy in certain cases.
