### ISSUE TITLE
tabs is not informed i feed

### ISSUE THREAD

**Issue by maves9** [circlecell/jsonlint.com#73]
dont know if it's actually a bug but i had quite an issue trouble shooting the problem in my own file.  would be nice if it had another response than undefined.

test code:
{
	"space": " ",
	"tab": "	"
}

**Comment by finom** [comment]
http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf

>  All code points may be placed within the quotation marks except for the code points that must be escaped: quotation mark (U+0022), reverse solidus (U+005C), and the control characters U+0000 to U+001F.

...

> \t represents the character tabulation character (U+0009).

So it isn't a bug.
