### ISSUE TITLE
Duplicate object keys/names is not an error

### ISSUE THREAD

**Issue by sr105** [circlecell/jsonlint.com#77]
`{"a":1,"a":2}`  https://jsonlint.com/?json={%22a%22:1,%22a%22:2}

This is probably just a bug in the online parser. According to past/closed issues, it should be a warning.

References: #6, #45, #52

**Comment by finom** [comment]
@sr105  excuse me, I've just checked your URL and it worked fine. Maybe you've used an old cached version if the app?
