### ISSUE TITLE
Does jsonlint.com store the data that we paste for formatting?

### ISSUE THREAD

**Issue by Gunner17** [circlecell/jsonlint.com#79]
Does jsonlint.com store the data that we paste in the editor for formatting inside the validator pane?

**Comment by darol100** [comment]
@Gunner17 , Looking over the network tab in the browser does not seem to make any extra call to a server to store this data. There are few tracking tools like Google Analytics but they track user activity no your JSON.

**Comment by finom** [comment]
@Gunner17 thank you for the question. @darol100 is right, we don't send your 
JSON anywhere.
