### ISSUE TITLE
Adverts can cover JSON input box

### ISSUE THREAD

**Issue by alexmccabe** [circlecell/jsonlint.com#90]
Some adverts cover the input box, their height is too tall. I am unable to get a screenshot as I now can't replicate, but I was unable to read `line 1` of the input box

**Comment by alexmccabe** [comment]
![add-overlay-issue](https://user-images.githubusercontent.com/2529110/121336597-9669a680-c913-11eb-9d1e-6912ed4be295.jpg)
Managed to replicate again

**Comment by toddynho** [comment]
should be fixed now
