### ISSUE TITLE
Comments in JSON are invalid

### ISSUE THREAD

**Issue by rtheil-growlink** [circlecell/jsonlint.com#99]
I've recently noticed that JSONlint doesn't accept any comments in the JSON, regardless of whether they are valid. The following JSON is valid in Postman, but JSONlint doesn't allow it. 

```
{
	"name": "Row 1 Test",
	"additionalDryBack": 1, //if additionalDryBack is provided, do not provide irrigationBeginDelay
	// "irrigationBeginDelay": 120, //if irrigationBeginDelay is provided, do not provide additionalDryBack
}
```
![image](https://user-images.githubusercontent.com/96268167/182889119-e69ba990-c1c6-4d2d-ae57-7af06a735f3f.png)

**Comment by hfrmobile** [comment]
That is correct, JSON does not support any comments!

You may use workaround like `"comment": "my comment..."` or use JSONC, which is "another format".

"JSON" and "JSON with Comments" are treaded separately.

But I agree that it would be nice when there will be JSONClint some day!
